services:

  db:
    image: postgres:18-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: super-secure-password
    ports:
      - "5432:5432"

volumes:
  postgres_data: