version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_PASSWORD: super-secure-password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    command: ["sh", "-c", "npm run migrate && npm run serve"]

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "4200:8080"
    depends_on:
      - server